### ISSUE TITLE
Add notebook examples and binder

### ISSUE THREAD

**Issue by jvail** [fredboudon/vmango#6]

**Comment by jvail** [comment]
Hi @fredboudon, the binder wont build. It complains about missing OpenGL drivers. I have added 
- mesa-libgl-cos6-x86_64
- mesa-libgl-devel-cos6-x86_64

here https://github.com/fredboudon/vmango/blob/add-binder/environment.yml
but still building pyopengl fails. Any idea which conda lib could fix this?

**Comment by jvail** [comment]
Alright - doing the "obvious" thing and install libgl in the binder docker did solve it. I had to create another file (apt.txt). I think we have two options:

- maintain a "binder" branch with the required files: apt.txt and environment.yml and keep master "clean"
- merge into master and use master for binder.

**Comment by fredboudon** [comment]
Using master seems a good solution for me. Moreover, apt.txt and environment.yml can be put into binder subdir. See for instance:
https://github.com/fredboudon/plantgl/tree/master/binder

**Comment by jvail** [comment]
Ok, good. Did not know that binder accepts a binder subdir.
